image:
  baseUrl: /upload/image/
  dir:
    path:
      format: xxxx/xx/xx/
  post:
    path: C:/travel/community/post/
  postUrl: /postfile/image/
  save:
    path: C:/travel/community/images/
logging:
  level:
    project:
      board:
        repository: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: project.board.entity

spring:  
  datasource:
    hikari:
      maximum-pool-size: 8
    initialization-mode: never
    password: 1234
    url: jdbc:mysql://localhost:3306/traveldb?serverTimezone=Asia/Seoul
    username: yjhn0715
  
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

  cache:
    cache-names: popular
    redis:      time-to-live: 600000 
    
  devtools:
    restart:
      enabled: true
      
  flyway:
    enabled: false
    
  resources:
    cache:
      period: 0
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  